### ISSUE TITLE
Unable to boot

### ISSUE THREAD

**Issue by WhittlesJr** [DerickEddington/nixos-config#1] opened 2024-12-10 19:40 UTC
Hi, 

I really like what you've done here. I've rebased my own nixos config on top of your repo, and modified it to fit your structure. Despite perhaps dozens of attempts with different BIOS option and hardware combinations, I am unable to use your install script and NixOS config. 

Although I can run the installer, and it seems to complete without issues, after a reboot, I find that the drives do not show up as a bootable option in the BIOS, for either legacy or UEFI. If I boot back into my live disk, and try to do a `zpool import` on any of the pools the script created, it dumps core. I've never seen that happen before with any zpools I've created by hand. 

I've tried on NVMEs and HDDs. If I do a stupid simple barebones NixOS installation by hand on a single disk, it works. 

Anyway, I don't know if this is worth your time to investigate, but I thought I'd share my experience.  Here is my branch:

https://github.com/WhittlesJr/nixos-config/compare/main...whittles-iskandar

**Comment by DerickEddington** [comment] 2024-12-11 20:39
Hi, Thanks.

Try uncommenting one, then only the other, then both, of these lines, until it hopefully works [*]:
https://github.com/DerickEddington/nixos-config/blob/b80cd9cfe5bae2e382ab2f5511064cf45544bc7c/per-host/yoyo/default.nix#L62-L63 (where yours will be in your `per-host/$HOSTHAME/default.nix`).  Let me know if that works or not.

#### Thoughts:

That a barebones NixOS installation on the same hardware works clearly shows that my approach is somehow triggering the issues.  But since I only used stable public options of NixOS, such low-level problems should not be occurring even if my stuff needs some improvement (I'd expect high-level errors preventing causing low-level problems), so I still suspect some weird bug(s) in something outside my stuff.

Maybe your UEFI has a bug (it happens, and my above suggestion can workaround such), or maybe your motherboard or drive controllers, or maybe (very unlikely) both your NVMEs and your HDDs, have some hardware problems, that causes both the not showing-up and the crashing of other things.

I think crashing of other things in the live installer can't be what's causing your drives to not show-up early at boot (since UEFI/BIOS doesn't involve commands nor ZFS yet at this earlier point), but I suppose it's possible that whatever problem is causing your drives to not show-up could also somehow be causing crashes (e.g. because of some really weird corner case they didn't cover).  The not showing-up is definitely a separate additional issue, but perhaps both are caused by a single deeper problem.

Just to mention:  If `zpool import` is indeed what crashed (as opposed to something else crashing at what seemed like the same time (see my newer comments in this thread)), that would be some serious bug in `zpool import`.  A crash of any program/process that dumps core is always a bug in that program or its dependencies.  I too have never seen that command crash before.  That should never occur (if programming was perfect), even if there's something very wrong with a drive or pool, or even if there's some flaw in my stuff (possible, and I'd want to find) - that's still some bug in OpenZFS that should be reported to them.  You can use the `coredumpctl` command, in the system where the crash occurs (i.e. when you've booted the live installer and just caused the crash), to list, export, and even use debugger on the core-dump file (`$ man coredumpctl`), as part of reporting the bug to the OpenZFS project.  Make sure you identify the one that has `zpool` as the EXE column value and the correct timestamp.  (For a core-dump file to be useful to them, they'd also need the exact `zpool` executable file and possibly the exact files of its library dependencies, which come from the particular build of the NixOS channel at whatever exact commit of Nixpkgs, which might be too difficult for both you and them to exchange, so it might be "easier" for them to try to reproduce themselves with the NixOS live installer, and/or for you to use a debugger (`gdb` by default) on the core dump, in your boot of the live installer where the crash occurs, so that you can get the backtrace(s) of the thread(s) and possibly investigate other aspects (like which signal caused the crash (e.g. SIGSEGV/SIGBUS vs SIGABRT), values of variables and memory, etc) so you can report (copy-paste debugger session) this essential info to them.  They should be able to help you dig into this if you're not familiar with this kind of debugging.  They'll definitely want to know about this bug.  Maybe it's already been reported but not yet fixed or a fix isn't in NixOS yet - search their issue tracker and report anyway if you're not sure.  I'd help report it but I'm unable to reproduce it.  Feel free to reference this issue, and follow-up to reference that from this - I'll want to follow that bug in OpenZFS too.)

[*]: Read my next comment also.

**Comment by DerickEddington** [comment] 2024-12-11 21:13
> Try uncommenting one, then only the other, then both, of these lines, until it hopefully works:

And also make sure you remove/comment-out/edit any other lines for those same options.  My repo has [one such immediately above](https://github.com/DerickEddington/nixos-config/blob/b80cd9cfe5bae2e382ab2f5511064cf45544bc7c/per-host/yoyo/default.nix#L59) those lines.  Otherwise there could be an error about conflicting values for the duplicated option.

**Comment by WhittlesJr** [comment] 2024-12-12 04:25
Thank you for the support! I will try your suggested fix and do my best to report the issue to OpenZFS. 

It might help if I gave a bit more context. Part of me wants to believe this is a hardware issue.
Before I found your repo, I was on a single NVME with ZFS root. One day, my system crashed, and I could no longer boot onto the NVME (it did not show up as a boot option, which looks just like the problem I'm having with this repo.) 

I went on to replace the motherboard, RAM, and NVME, moving to a dual-NVME setup. I found your repo and migrated to it, as I mentioned, but could never get it to work despite the new hardware. 

I still don't have any solid theories about what's going on here, and I've tried a Lot of Things™.

**Comment by DerickEddington** [comment] 2024-12-12 06:11
> I will try [to] do my best to report the issue to OpenZFS.

Instead of what I'd suggested above for how to get the debugger info, I realized you probably can configure your running NixOS live installer and your local network to allow other people to SSH into that live installer while it's still running, so they can then use a debugger on the crashing `zpool import` themselves.  You'll need their public key and to configure your firewall(s) of course, and your machine would be tied-up waiting, but this might be the easiest way for the OpenZFS people to get the essential details.

If you like, I could SSH in and do some initial debugger'ing of it and save the session of whatever I find, to go with your report.  I can give you my public key and my IP address, and we can coordinate, over some other private messaging channel.  This way, your machine is not tied-up waiting as long, and we'll have something more substantial to report initially.

**Comment by DerickEddington** [comment] 2024-12-12 06:48
> and I could no longer boot onto the NVME (it did not show up as a boot option, which looks just like the problem I'm having with this repo.)
> 
> I went on to replace the motherboard, RAM, and NVME, moving to a dual-NVME setup.

Thanks for mentioning this.  It adds a little more suspicion to a hardware problem being the cause, but it's still unclear.

Have you tried using your two NVMEs as dual as installed on by some other OS (e.g. Ubuntu, Fedora, Windoze) and/or installed on as NixOS but non-ZFS but still dual (e.g. RAID)?

Or, if you can have your HDD(s) along with your NVMEs physically installed at the same time, you could then try installing barebones OS as non-ZFS on a single HDD, boot into that, then see if you can manually create a zpool across both NVMEs and then see if `zpool import` works that way.

Doing either or both of those, to find-out whatever happens, would be useful to narrow-down what's going on.

I wonder if your hardware only has the problem when attempting to use dual NVMEs vs one being left unpartitioned while both are physically present.  Maybe your UEFI chokes on seeing multiple bootable EFI System Partitions and/or on just seeing multiple drives partitioned.  But maybe when only one is partitioned but not the other (i.e. the partition table was overwritten with zeros or randomness) then it works.  (My installation script does zap the partition tables initially and when aborting, which could've left your drives unpartitioned and so ready to work, under this assumption, when you install barebones on only one.)  UEFI looks at partition tables very early during boot, and some UEFIs are somewhat buggy and/or only support old EFI standards and/or cut corners and lack full support for less-commonly-needed abilities of the EFI standard (IIRC).  If a UEFI bug screws-up its view of a drive at boot, that might screw-up later attempts to use it by OS drivers (IIRC) (which maybe triggers the `zpool import` bug somehow).

Sometimes you can find newer updated versions of your UEFI's firmware from its vendor, which can be more or less easy/frustrating, depending on the vendor and hardware, to "flash" the updated image into your firmware to have a newer version of the UEFI with their newer bug fixes.

**Comment by DerickEddington** [comment] 2024-12-12 17:41
You wrote in the title of this issue:
> importing zpools cause kernel panic

Is that in addition to, and when, `zpool import` crashes and dumps core?

**Comment by WhittlesJr** [comment] 2024-12-12 18:07
I will try some experiments with creating mirrored pools by hand with my NVMEs and installing something simple on them. If you're really keen on this I'd be happy to pair with you over Discord and share my screen from my other machine. 

It may not be exactly a kernel panic, actually... usually you do see the phrase "kernel panic" in the output in such instances, don't you? But this is what I'm actually getting:

```
Broadcast message from systemd-journald@nixos 
systemd[1]: Caught <ABRT>, core dump failed (child 2008, code=killed, status=6/ABRT).
Broadcast message from systemd-journald@nixos 
systemd[1]: Freezing execution.
```

I'm also just now noticing that the core dump failed, heh. Not sure how much helpful information we can get out of this system...

**Comment by DerickEddington** [comment] 2024-12-12 22:45
I've tested that core dumps are configured to succeed, in the 24.11 live installer (i.e. the live installer isn't configured to prevent them).  This suggests that the "core dump failed" error you had is very weird because core dumping should be working there.  I found an unofficial mention that says systemd will sometimes give the "core dump failed" error when there's an unusual hardware problem with the drive where it would've written the core dump.  But in the live installer, that location, `/var/lib/systemd/coredump/`, is in a `tmpfs` RAM-backed FS, which means such a "drive" problem would actually be a problem with the RAM I guess.  

(I found that a different error occurs when there's not enough space left in the FS to save a core dump, so it seems that your case couldn't have been due to lack of space.)

**Comment by DerickEddington** [comment] 2024-12-13 00:22
> ```
> systemd[1]: Freezing execution.
> ```

I think this means that there's a different, deeper, worse problem, and not `zpool import` crashing.  systemd freezing itself (I confirmed that's what that message is) means it encountered some very weird unrecoverable problem (IIUC).  That shouldn't be happening if it was just failing to handle the core dumping of a user process crashing.

> ```
> systemd[1]: Caught <ABRT>, core dump failed (child 2008, code=killed, status=6/ABRT).
> ```

I've just read a little of systemd's source-code of where this `core dump failed` error comes from.  It's actually from when a systemd process itself has crashed and is attempting to dump core in a special way (for systemd being special).  That error message means there was some problem (in addition to whatever original problem caused the crash) doing the special way (which involves forking (which is what the `child 2008` PID is - that's a systemd process) to actually be the one to die with core dump).

It's not about a user command like `zpool` crashing.

The `ABRT` part of the error message means a systemd process got SIGABRT, which usually happens when a process called `abort()` on itself, which often is when something like an `assert()` failed.  This suggests that a systemd program had an assertion fail (which is supposed to never happen) or encountered some very weird unrecoverable situation where it can only abort.  It's very unlikely that my stuff for installing and nixos config could somehow cause that.  systemd tries as much as possible to continue running no matter what other stuff fails, and it only aborts and freezes when something very weird and low-level is screwed-up with the machine.

> ```
> Broadcast message from systemd-journald@nixos 
> ```

That it broadcast the error message to all users' terminals is also indicative of the very weird emergency severity of systemd crashing.  It doesn't do such broadcasting when only a user process had a failure to save a core dump.

> Not sure how much helpful information we can get out of this system...

Yeah, I'm now more strongly suspecting that your hardware is faulty.  Or, I suppose there's a tiny chance that systemd has a bug causing it to crash and your particular machine triggers that but most other machines don't somehow (if that's the case, I can't help with that).

Did you actually see a `zpool import` command crash and say it dumped core?  That would look something like the following in your shell session in your terminal:
```shell
$ zpool import $POOL
...
Segmentation fault (core dumped)
```
or:
```shell
$ zpool import $POOL
...
Aborted (core dumped)
```
or other possible reasons prefixed before the ` (core dumped)` part.

You would've seen such a message, as if it was output by the command, in the same terminal where you invoked the command.  Regardless of whatever other log messages about systemd are generated.

If you didn't see such, then I think we must change our assessment to no longer consider `zpool import` to have crashed.

EDITED: Corrected typos, and made clarifications.

**Comment by DerickEddington** [comment] 2024-12-13 03:00
> usually you do see the phrase "kernel panic" in the output in such instances, don't you?

Whether such a phrase is output, when the kernel panics, depends on whether the terminal you're working in is the console or not.  If you're SSH'ed in, then it's not the console, and so you'll never see any message upon kernel panic.  This is because the console is the only safe place that can be output to after a panic.  The console is what you see when you press Ctrl-Alt-F1 - i.e. where you get just a basic textual terminal directly on your monitor without the GUI desktop environment.

The reliable way to review kernel-panic logs is to look in `/sys/fs/pstore/` (before they're archived) and `/var/lib/systemd/pstore/` (after archived) [[1]](https://blogs.oracle.com/linux/post/pstore-linux-kernel-persistent-storage-file-system), after rebooting the panicked-frozen system.

When a kernel panic occurs, the entire system becomes completely frozen immediately, sometimes after your monitor changes to all black.  If you weren't already viewing the console when it freezes, you'll never see anything about the panic, it'll just freeze wherever you were.  If you didn't experience such a freeze, then kernel panic didn't occur - i.e. if you were able to continue running commands or doing anything else after whatever incident, then it wasn't a panic.

You should check those directories I listed above, and if you have any files in them whose timestamps correspond to when you were trying to install my approach, let me know and attach the files.  You can check `/sys/fs/pstore/` from a boot of a live installer - that location represents special non-volatile storage provided by your motherboard.  But if you've booted any installed OS that uses `systemd-pstore.service` (e.g. NixOS or any other Linux that uses systemd), then that would've moved the files to the archive location at `/var/lib/systemd/pstore/` in whatever FS was setup for that installed system (which if you've since wiped-out that then any panic logs are now gone forever).

**Comment by DerickEddington** [comment] 2024-12-13 03:07
> Try uncommenting one, then only the other, then both, of these lines, until it hopefully works [*]:
> 
> https://github.com/DerickEddington/nixos-config/blob/b80cd9cfe5bae2e382ab2f5511064cf45544bc7c/per-host/yoyo/default.nix#L62-L63 (where yours will be in your `per-host/$HOSTHAME/default.nix`).
> Let me know if that works or not.

Just a reminder to try those - there's a chance that'll make everything work for your hardware.

No rush with this or my other suggestions.

**Comment by DerickEddington** [comment] 2024-12-17 19:47
> Did you actually see a `zpool status` command crash and say it dumped core? That would look something like the following in your shell session in your terminal:

Oops.  I meant `zpool import`.  I've corrected my above comment for this.  Sorry if that was confusing.

I'd also edited some of my comments to reflect my newer uncertainty about whether it was a `zpool` command that crashed.

**Comment by DerickEddington** [comment] 2024-12-30 23:31
If you find new evidence that my approach is causing your issue, we can re-open this.

**Closed as completed by DerickEddington** 2024-12-30 23:31 UTC
